Combine/Combine/Controllers/FileManagerController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Combine.Controllers
{
    public class FileManagerController : Controller
    {
        // GET: FileManager
        string auth;
       

        public ActionResult Index()
        {
            
            HttpClient cli = new HttpClient();
            cli.DefaultRequestHeaders.Add("UserName", "mmr");
            cli.DefaultRequestHeaders.Add("Password", "MMR");
            var ts = cli.PostAsync("http://localhost:52357/token", new StringContent("grant_type=password", encoding: Encoding.UTF8, mediaType: "application/json"));
            ts.Wait();
            HttpResponseMessage res = ts.Result;
            var read = res.Content.ReadAsStringAsync();
            read.Wait();
            string data = read.Result;
            var resData = JsonConvert.DeserializeObject<AuthRes>(data);
            auth = resData.access_token;
            Session["auth"] = auth;


            return View();
        }

        public ActionResult GoFolder(string dpath)
        {
            IsLogin();
            string Id = Session["username"].ToString();
            string path = Path.Combine(Server.MapPath("~/Uploads/"), Id + dpath);
            int pos = path.IndexOf("Uploads");
            string showpath = path.Substring(pos+8);
            var files = Directory.GetFiles(path);
            var folders = Directory.GetDirectories(path);
            List<string> filepaths = new List<string>();
            List<string> filenames = new List<string>();
            List<long> filelengths = new List<long>();
            List<string> fileext = new List<string>();
            List<string> folderpaths = new List<string>();
            List<string> foldernames = new List<string>();


            foreach (var file in files)
            {
                FileInfo fileInfo = new FileInfo(file);
                filelengths.Add(fileInfo.Length);
                fileext.Add(fileInfo.Extension);
                filenames.Add(fileInfo.Name);
                filepaths.Add(fileInfo.FullName);
            }

            foreach (var folder in folders)
            {
                DirectoryInfo directoryInfo = new DirectoryInfo(folder);
                foldernames.Add(directoryInfo.Name);
                folderpaths.Add(directoryInfo.FullName);


            }
            string combindedString = string.Join(",", filenames);
            ViewBag.filepaths = filepaths;
            ViewBag.fileexts = fileext;
            ViewBag.filelengths = filelengths;
            ViewBag.filenames = filenames;
            ViewBag.foldernames = foldernames;
            ViewBag.folderpaths = folderpaths;
            ViewBag.dpath = dpath;
            ViewBag.st = combindedString;
            ViewBag.path = path;
            ViewBag.showpath = showpath;
            return View();
        }

        public JsonResult SearchFile(string filename, string dpath)
        {
            string path = Path.Combine(Server.MapPath("~/Uploads/"), Session["username"].ToString() + dpath);


            var files = Directory.GetFiles(path, "*" + filename + "*");

            return Json(files, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetUrl(string filename)
        {

            string username = Session["username"].ToString();
            string type = Path.GetExtension(filename);
           
            string json = JsonConvert.SerializeObject(new { username, filename,type });
            HttpClient cli = new HttpClient();
            cli.DefaultRequestHeaders.Add("Authorization", "bearer " + (string)Session["auth"]);
            //var ts = cli.PostAsync("http://localhost:52357/rssApi/files/filename", new StringContent(json, encoding: Encoding.UTF8, mediaType: "application/json"));

           var ts = cli.GetAsync("http://localhost:52357/rssApi/files/filename?username="+username+"&filename="+filename+"&type="+type);
            ts.Wait();
            HttpResponseMessage res = ts.Result;

            var read = res.Content.ReadAsStringAsync();
            read.Wait();
            string data = read.Result;
            var resData = JsonConvert.DeserializeObject<string>(data);

            if (resData == "File Not Found.")
            {
                ViewBag.url = resData;

            }
            else
            {
                string url = "https://localhost:44397/Upload/GetFile?filetoken=" + resData;
                ViewBag.url = url;
            }
            return View();
        }

        public ActionResult ViewDetails(string filename, string dpath)
        {
            IsLogin();
            string filepath = Path.Combine(Server.MapPath("~/Uploads/"), Session["username"].ToString() + @"\" + dpath + @"\" + filename);
            FileInfo fileInfo = new FileInfo(filepath);
            long l=(fileInfo.Length)/1048576;
            string ext=(fileInfo.Extension);
            int pos = filepath.IndexOf("Uploads");
            string showpath = filepath.Substring(pos + 8);
            DateTime dt = fileInfo.LastWriteTime;
            DateTime ut = fileInfo.CreationTime;
            ViewBag.filename = filename;
            ViewBag.l = l;
            ViewBag.ext = ext;
            ViewBag.showpath = showpath;
            ViewBag.dt = dt;
            ViewBag.ut = ut;
            ViewBag.user = Session["username"].ToString();
           
            return View();
        }
        public ActionResult DownloadFile(string filename, string dpath)
        {
            string currentpath = Path.Combine(Server.MapPath("~/Uploads/"), Session["username"].ToString() + @"\" + dpath);
            string filepath = Path.Combine(Server.MapPath("~/Uploads/"), Session["username"].ToString() + @"\" + dpath + @"\" + filename);


            string ext = Path.GetExtension(filename);
            string mime = null;
            switch (ext)
            {
                case ".jpg":
                case ".jpeg":
                    mime = "image/jpeg";
                    break;
                case ".pdf":
                    mime = "application/pdf";
                    break;
                case ".mp4":
                    mime = "video/mp4";
                    break;
                case ".zip":
                    mime = "application/zip";
                    break;
                case ".xlsx":
                    mime = "text/csv";
                    break;
                case ".docx":
                    mime = "application/vnd.openxmlformats-officedocument.wordprocessing";



                    break;
                default:
                    mime = "html/text";
                    break;


            }
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);

            Response.AppendHeader("Content-Disposition", "inline; filename=" + filename);
            return File(fileBytes, mime);
        }

        public void IsLogin()
        {
            if (Session["login"].ToString() != "true")
            {
                RedirectToAction("Login", "User");
            }

        }
        public ActionResult ShowPlan()
        {
            IsLogin();
            HttpClient cli = new HttpClient();
            cli.DefaultRequestHeaders.Add("Authorization", "bearer " + (string)Session["auth"]);
            var ts = cli.GetAsync("http://localhost:52357/rssApi/plans/all");
            ts.Wait();
            HttpResponseMessage res = ts.Result;

            var read = res.Content.ReadAsStringAsync();
            read.Wait();
            string data = read.Result;


            DataTable datatable = JsonConvert.DeserializeObject<DataTable>(data);



            return View(datatable);
        }

        partial class AuthRes
        {
            public string access_token { get; set; }
            public int expires_in { get; set; }
            public string token_type { get; set; }
        }
    }
}

Combine/Combine/Views/FileManager/GetUrl.cshtml
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12" style="display:flex">

                <div class="navbar-header">
                    <button class="navbar-toggle" data-target="#mobile_menu" data-toggle="collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a href="#" class="navbar-brand">SHARX</a>
                </div>

                <div class="navbar-collapse collapse" id="mobile_menu">
                    <ul class="nav navbar-nav" style="display:block">
                        <li class="active"><a href="#">Home</a></li>


                        <li><a href="#">Welcome</a></li>
                        <li><a href="#">Services</a></li>

                    </ul>
                    <ul class="nav navbar-nav" style="display:block">
                        <li>
                            <form action="" class="navbar-form">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="search" name="search" id="searchfiles" placeholder="Search Files Here..." class="form-control">

                                        <ul id="myUL" class="list-group-item-info">
                                        </ul>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right" style="display:block">
                        <li><span class="glyphicon glyphicon-user"></span> @Html.ActionLink(Session["username"].ToString(), "Logout", "User") </li>
                        <li>
                            <span class="glyphicon glyphicon-log-in"></span> @Html.ActionLink("Log Out", "Logout", "User") <span class="caret"></span>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<h2>Share Url  </h2>

<div id="urlarea" class="wrap-input100 validate-input" data-validate="First Name is required">
    <input class="input100" type="text" id="url" value="@ViewBag.url" readonly>
    <span class="focus-input100"></span>
</div>
<button style="color:white!important" class="btn-outline-success rounded-pill" id="clipboard" onclick="myFunction()">Copy to Clipboard</button>
<script>
    function myFunction() {
        var copyText = document.getElementById("url");
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
        alert("Copied the Link to clipboard: " + copyText.value);
    }
</script>

Combine/Combine/Views/FileManager/GoFolder.cshtml
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

@{
    ViewBag.Title = "GoFolder";
    var filepaths = ViewBag.filepaths;
    var fileexts = ViewBag.fileexts;
    var filelengths = ViewBag.filelengths;
    var filenames = ViewBag.filenames;
    var foldernames = ViewBag.foldernames;
    var folderpaths = ViewBag.folderpaths;
    var dpath = ViewBag.dpath;
    var ext = "";
    var imagepath = "";
    int c = 0;
    var showpath = ViewBag.showpath;

}

<!--nav bar



    -->
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12" style="display:flex">

                <div class="navbar-header">
                    <button class="navbar-toggle" data-target="#mobile_menu" data-toggle="collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a href="#" class="navbar-brand">SHARX</a>
                </div>

                <div class="navbar-collapse collapse" id="mobile_menu">
                    <ul class="nav navbar-nav" style="display:block">
                        <li class="active"><a href="#">Home</a></li>


                        <li><a href="#">Welcome</a></li>
                        <li><a href="#">Services</a></li>

                    </ul>
                    <ul class="nav navbar-nav" style="display:block">
                        <li>
                            <form action="" class="navbar-form">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="search" name="search" id="searchfiles" placeholder="Search Files Here..." class="form-control">

                                        <ul id="myUL" class="list-group-item-info">
                                        </ul>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right" style="display:block">
                        <li><span class="glyphicon glyphicon-user"></span> @Html.ActionLink(Session["username"].ToString(), "GetPlan", "User") </li>
                        <li>
                            <span class="glyphicon glyphicon-log-in"></span> @Html.ActionLink("Log Out", "Logout", "User") <span class="caret"></span>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>








<!-- nav-->



<p class="round2">@showpath</p>

<div id="content" style="top: 222px; left: 665px; position: absolute;">

    <div class="grid-container1">
        @foreach (string f in foldernames)
        {
            <div class="card1">
                @Html.ActionLink(" ", "GoFolder", new { dpath = dpath + @"\\" + f })
                <!-- added
                -->
                <h3 class="title1" style="font-size:14px;">@f   </h3>

                <div class="bar1">

                    <div class="filledbar1"></div>
                </div>
                <img class="img_height" src="~/Content/folder.png">

            </div>




        }

        @foreach (string f in filenames)
        {

            {
                ext = f.Substring((f.LastIndexOf(".")));
                switch (ext)
                {
                    case ".pdf":
                        imagepath = "/Content/pdf.png";
                        break;
                    case ".ppt":
                        imagepath = "/Content/ppt.png";
                        break;
                    case ".docx":
                    case ".doc":
                        imagepath = "/Content/word.png";
                        break;
                    case ".zip":
                        imagepath = "/Content/zip.png";
                        break;
                    case ".mp4":
                        imagepath = "/Content/video.png";
                        break;
                    case ".xlsx":
                    case ".xls":
                        imagepath = "/Content/excel.png";
                        break;

                    default:
                        imagepath = "/Content/file.png";
                        break;

                }

            }
         <input type="file" class="filepond"
               name="filepond"
               data-max-file-size="3000MB"
               data-max-files="10">
            <div class="card1">
                <!-- added
                -->
                <div class="container1">
                    <div class="more" onclick="showm(this.id)" id="more_@c">
                        <button id="more-btn" class="more-btn">
                            <span class="more-dot"></span>
                            <span class="more-dot"></span>
                            <span class="more-dot"></span>
                        </button>
                        <div class="more-menu">
                            <div class="more-menu-caret">
                                <div class="more-menu-caret-outer"></div>
                                <div class="more-menu-caret-inner"></div>
                            </div>
                            <ul class="more-menu-items" tabindex="-1" role="menu" aria-labelledby="more-btn" aria-hidden="true">
                                <li class="more-menu-item" role="presentation">
                                    <button type="button" class="more-menu-btn" role="menuitem">@Html.ActionLink("ViewDetails", "ViewDetails", new { filename = f, dpath = dpath })</button>
                                </li>
                                <li class="more-menu-item" role="presentation">
                                    <button type="button" class="more-menu-btn" role="menuitem">@Html.ActionLink("Download", "DownloadFile", new { filename = f, dpath = dpath })</button>
                                </li>
                                <li class="more-menu-item" role="presentation">
                                    <button type="button" class="more-menu-btn" role="menuitem"> @Html.ActionLink("Share", "GetUrl", new { filename = f })</button>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>



                <!-- end
                -->
                <h3 class="title1" style="font-size:14px;">@f   </h3>

                <div class="bar1">

                    <div class="filledbar1"></div>
                </div>
                <img class="img_height" src="@imagepath">

            </div>





            c++;

        }
    </div>

</div>
<script>
    var l= @ViewBag.l + 1;
        var res = null;
    $(document).ready(function () {
        $(function () {
            $('#searchfiles').keyup(function (event) {
                event.preventDefault();
                    var filename = $('#searchfiles').val();
                $.ajax({
                    type: "GET",
                    url: "/FileManager/SearchFile",
                    data: { 'filename': filename , 'dpath': '@dpath' },
                    dataType: "json",

                    success: function (data) {
                            somefunction(data);
                        },
                    error: function() {
                            alert("Error occured!!")
                    }
                    });
                    console.log("result of res" + res);
                })
        })
    });

    function somefunction(data)
    {
        var lis = null;

        var ul = document.getElementById("myUL");
        while(( lis = ul.getElementsByTagName("li")).length > 0) {
	        ul.removeChild(lis[0]);
        }
        for (i = 0; i <= data.length; i++) {

            var res = data[i].split("\\").slice(-1);

            $("#myUL").append('<li><a href="DownloadFile?dpath=@dpath&?filename='+res+'">' + res + '</a></li>');
        }
    }

    var names = "@ViewBag.st";
  /*  function searchFileFun(req)
    {

        var dummy=req.value;
        var final = "";
        var filenames= names.split(",");
        for(var i=0;i<filenames.length;i++)
        {
	        if(filenames[i].indexOf(dummy) != -1)
	        {
		        final= final + filenames[i] + ",";
	        }

        }

    }
    */

   // var visible = false;
    function showm(ele) {
        var el = document.querySelector("#"+ele);

        var menu = el.querySelector('.more-menu');
        if (el.classList.contains('show-more-menu')) {
      //      visible = true;
            el.classList.remove('show-more-menu');
        menu.setAttribute('aria-hidden', true);
       // document.addEventListener('mousedown', hideMenu, false);
        }
        else{

        el.classList.add('show-more-menu');
        menu.setAttribute('aria-hidden', false);
       // document.addEventListener('mousedown', hideMenu, false);
    }

    }


var visible = false;

function showMenu(e) {
    e.preventDefault();
    if (!visible) {
        visible = true;
        el.classList.add('show-more-menu');
        menu.setAttribute('aria-hidden', false);
        document.addEventListener('mousedown', hideMenu, false);

    }
    }


function hideMenu(e) {

    if (visible) {
        visible = false;
        el.classList.remove('show-more-menu');
        menu.setAttribute('aria-hidden', true);
        document.removeEventListener('mousedown', hideMenu);
    }
}


</script>

Combine/Combine/Views/FileManager/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Folder","GoFolder","FileManager")
<h2>Index</h2>

Combine/Combine/Views/FileManager/ShowPlan.cshtml
@{
    ViewBag.Title = "ShowPlan";
}

<h2>ShowPlan</h2>

<div>
    <h4>PlanModel</h4>
     <table class="table table-hover table-dark">
        <thead>
            <tr>
                @foreach (System.Data.DataColumn co in Model.Columns)
                {
                    <th>  co.Caption </th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (System.Data.DataRow row in Model.Rows)
            {
                <tr>
                    @foreach (var cell in row.ItemArray)
                    {
                        <td>@cell.ToString()</td>
                    }
                </tr>
            }
        </tbody>
    </table>

Combine/Combine/Views/FileManager/ViewDetails.cshtml
@{
    ViewBag.Title = "ViewDetails";
    var filename = ViewBag.filename;
    var l = ViewBag.l;
    var ext = ViewBag.ext;
    var showpath = ViewBag.showpath;
    var dt = ViewBag.dt;
    var ut = ViewBag.ut;
    var user = ViewBag.user;
    var imagepath = "";
    switch (ext)
    {
        case ".pdf":
            imagepath = "/Content/pdf.png";
            break;
        case ".ppt":
            imagepath = "/Content/ppt.png";
            break;
        case ".docx":
        case ".doc":
            imagepath = "/Content/word.png";
            break;
        case ".zip":
            imagepath = "/Content/zip.png";
            break;
        case ".mp4":
            imagepath = "/Content/video.png";
            break;
        case ".xlsx":
        case ".xls":
            imagepath = "/Content/excel.png";
            break;

        default:
            imagepath = "/Content/file.png";
            break;

    }
}
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12" style="display:flex">

                <div class="navbar-header">
                    <button class="navbar-toggle" data-target="#mobile_menu" data-toggle="collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a href="#" class="navbar-brand">SHARX</a>
                </div>

                <div class="navbar-collapse collapse" id="mobile_menu">
                    <ul class="nav navbar-nav" style="display:block">
                        <li class="active"><a href="#">Home</a></li>


                        <li><a href="#">Welcome</a></li>
                        <li><a href="#">Services</a></li>

                    </ul>
                    <ul class="nav navbar-nav" style="display:block">
                        <li>
                            <form action="" class="navbar-form">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="search" name="search" id="searchfiles" placeholder="Search Files Here..." class="form-control">

                                        <ul id="myUL" class="list-group-item-info">
                                        </ul>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right" style="display:block">
                        <li><span class="glyphicon glyphicon-user"></span> @Html.ActionLink(Session["username"].ToString(), "Logout", "User") </li>
                        <li>
                            <span class="glyphicon glyphicon-log-in"></span> @Html.ActionLink("Log Out", "Logout", "User") <span class="caret"></span>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-30 p-r-30 p-t-20 p-b-20">
            <form class="login100-form validate-form flex-sb flex-w" action="Login" method="post">
                <span class="login100-form-title p-b-40">

                    View Details
                </span>
                <div id="img-container" style=" width: 100%;height: max-content;display: flex;justify-content: center;">
                    <div id="img">
                        <img src="@imagepath">
                    </div>
                </div>

                <div class="p-t-25 p-b-9">
                    <span style="font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        File Name  -: @filename
                    </span>
                </div>

                <div class="p-t-25 p-b-9" style="display:block!important">
                    <span style="display:block!important;font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        Length  -: @l  MB
                    </span>
                </div>


                <div class="p-t-25 p-b-9" style="display:block!important">
                    <span style="display:block!important;font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        Extension  -: @ext
                    </span>
                </div>

                <div class="p-t-25 p-b-9" style="display:block!important">
                    <span style="display:block!important;font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        Last Modified Time  -: @dt
                    </span>
                </div>
                <div class="p-t-25 p-b-9" style="display:block!important">
                    <span style="display:block!important;font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        Creation Time -: @ut
                    </span>
                </div>
                <div class="p-t-25 p-b-9" style="display:block!important">
                    <span style="display:block!important;font-size:20px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
                        User  -: @user
                    </span>
                </div>



            </form>
        </div>
    </div>
</div>